let productos = {
    "tittle": "Cris B Music Shop",
    "status": "available",
    "products” : ":([
        {
            "id": 1,
            "category": "wear",
            "name": "Cris B Essentials Cap",
            "year": 2022,
            "author": "Cris B",
            "price": 25.00,
            "color": "Black",
            "description": "One Size. Unisex",
            "image": "https://i.imgur.com/NOPTkIm.jpg",
        },
        {
            "id": 2,
            "category": "wear",
            "name": "Dunkler Stier Essentials Cap",
            "year": 2022,
            "author": "Cris B",
            "price": 25.00,
            "color": "Black",
            "description": "One Size. Unisex",
            "image": "https://i.imgur.com/hcTy3zw.jpg",
        },
        {
            "id": 3,
            "category": "wear",
            "name": "Dunkler Stier Sweatshirt",
            "year": 2022,
            "author": "Cris B",
            "price": 60.00,
            "color": "Black",
            "description": "Unisex. Sweatshirt. Oversized fit. 100% Polyester",
            "image": "https://i.imgur.com/GMTX5FI.jpg",
        },
        {
            "id": 4,
            "category": "wear",
            "name": "Cris B Sweatshirt",
            "year": 2022,
            "author": "Cris B",
            "price": 60.00,
            "color": "Black",
            "description": "Unisex. Sweatshirt. Oversized fit. 100% Polyester",
            "image": "https://i.imgur.com/dcugDtb.jpg",
        },
        {
            "id": 5,
            "category": "article",
            "name": "Cris B Set Mug",
            "year": 2022,
            "author": "Cris B",
            "price": 15.00,
            "color": "Black/White",
            "description": "One Size. Ceramic.",
            "image": "https://i.imgur.com/HtyXuwR.jpg",
        },
        {
            "id": 6,
            "category": "article",
            "name": "Dunkler Stier Set Mug",
            "year": 2022,
            "author": "Cris B",
            "price": 15.00,
            "color": "Black/White",
            "description": "One Size. Ceramic.",
            "image": "https://i.imgur.com/eeKXNZM.jpg",
        },
        {
            "id": 7,
            "category ":"article",
            "name": "Cris B Stickers",
            "year": 2022,
            "author": "Cris B",
            "price": 2.00,
            "color": "Black",
            "description": "One Size. Two adhesives included.",
            "image": "https://i.imgur.com/EkcERrc.jpg",
        },
        {
            "id": 8,
            "category": "article",
            "name": "Dunkler Stier Stickers",
            "year": 2022,
            "author": "Cris B",
            "price": 2.00,
            "color": "Black",
            "description": "One Size. Two adhesives included.",
            "image": "https://i.imgur.com/jSWsrKS.jpg",
        },
        {
            "id": 9,
            "category": "wear",
            "name": "Cris B Essentials Tee",
            "year": 2022,
            "author": "Cris B",
            "price": 40.00,
            "color": "Black",
            "description": "Unisex. Oversized fit. 100% Cotton.",
            "image": "https://i.imgur.com/jx6pWfM.jpg",
        },
        {
            "id": 10,
            "category": "wear",
            "name": "Dunkler Stier Essentials Tee",
            "year": 2022,
            "author": "Cris B",
            "price": 40.00,
            "color": "Black",
            "description": "Unisex. Oversized fit. 100% Cotton.",
            "image": "https://i.imgur.com/GEvJIDR.jpg",
        },
        {
            "id": 11,
            "category": "Ep",
            "name": "Hurricane Fall",
            "year": 2019,
            "author": "HKJ",
            "price": 12.00,
            "color": null,
            "description": "12' vinyl. Techno.",
            "image": "https://i.imgur.com/9D53KhW.jpg",
        },
        {
            "id": 12,
            "category": "Ep",
            "name": "Back To Shine",
            "year": 2019,
            "author": "HKJ",
            "price": 12.00,
            "color": null,
            "description": "12' vinyl. Techno.",
            "image": "https://i.imgur.com/qzIoR4y.jpg",
        },
        {
            "id": 13,
            "category": "Ep",
            "name": "Under Death",
            "year": 2020,
            "author": "HKJ",
            "price": 12.00,
            "color": null,
            "description": "12' vinyl. Techno.",
            "image": "https://i.imgur.com/0rjwkAF.jpg",
        },
        {
            "id": 14,
            "category": "Ep",
            "name": "Alarm State",
            "year": 2020,
            "author": "HKJ",
            "price": 12.00,
            "color": null,
            "description": "12' vinyl. Techno.",
            "image": "https://i.imgur.com/2AFxMLw.jpg",
        },
        {
            "id": 15,
            "category": "Ep",
            "name": "Brutal",
            "year": 2021,
            "author": "HKJ",
            "price": 12.00,
            "color": null,
            "description": "12' vinyl. Techno.",
            "image": "https://i.imgur.com/aFfX9wm.jpg",
        },
        {
            "id": 16,
            "category": "Ep",
            "name": "Occasion",
            "year": 2021,
            "author": "HKJ",
            "price": 12.00,
            "color": null,
            "description": "12' vinyl. Techno.",
            "image": "https://i.imgur.com/YKLuCmD.jpg",
        },
    ])
}
console.log(JSON.stringify(productos))

export default productos;
